# Generated by Django 5.2.6 on 2026-01-05 17:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_libro', models.CharField(max_length=500, verbose_name='Título del libro')),
                ('puntuacion', models.FloatField(help_text='Valoración de 1.0 a 10.0 estrellas', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Puntuación')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de valoración')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['usuario', '-fecha'], name='main_valora_usuario_0d8b4d_idx'), models.Index(fields=['titulo_libro'], name='main_valora_titulo__12c6b0_idx')],
                'unique_together': {('usuario', 'titulo_libro')},
            },
        ),
    ]
