# Generated by Django 5.2.6 on 2026-01-05 19:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('autor', models.CharField(blank=True, max_length=300, verbose_name='Autor')),
                ('portada', models.URLField(blank=True, max_length=1000, verbose_name='Portada')),
                ('genero', models.CharField(blank=True, max_length=100, verbose_name='Género')),
                ('sinopsis', models.TextField(blank=True, verbose_name='Sinopsis')),
                ('estado', models.CharField(choices=[('por_leer', 'Por leer'), ('leido', 'Leído')], default='por_leer', max_length=20, verbose_name='Estado')),
                ('valoracion', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Mi valoración')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('fecha_leido', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_guardados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Libro de usuario',
                'verbose_name_plural': 'Libros de usuarios',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('usuario', 'titulo')},
            },
        ),
    ]
